on: push
name: Build, Test, and Publish
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: actions/npm@master
      with:
        args: install
      if: contains(github.ref, 'tags/v')
    - name: Test
      uses: actions/npm@master
      with:
        args: test
      if: contains(github.ref, 'tags/v')
    - name: Publish
      uses: actions/npm@master
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: publish --access public
      if: contains(github.ref, 'tags/v')
